name: Docs PR Check

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and plugins
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-mermaid2-plugin

      - name: Build docs
        run: mkdocs build --strict

      - name: Upload built site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
