name: Docs → GitHub Wiki

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout Wiki repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: Sync Markdown docs to Wiki (set Home.md)
        run: |
          set -e
          # Clean wiki directory except .git
          find wiki -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          # Copy markdown sources
          cp -r docs/* wiki/
          # Set homepage
          if [ -f docs/index.md ]; then
            cp docs/index.md wiki/Home.md
          fi
          # Ensure sidebar exists
          if [ ! -f wiki/_Sidebar.md ]; then
            printf '%s\n' \
              '* [Home](Home)' \
              '* [Архитектура](architecture/er-schema.md)' \
              '* [Многотенантность и контекст](architecture/multitenancy.md)' \
              '* [RBAC](services/rbac.md)' \
              '* [Миграции (Liquibase)](backend/migrations.md)' \
              > wiki/_Sidebar.md
          fi

      - name: Commit and push to Wiki
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update wiki from push $GITHUB_SHA"
            git push
          fi
