name: Docs → GitHub Wiki

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout Wiki repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: Sync Markdown docs to Wiki (set Home.md)
        run: |
          set -e
          # Clean wiki directory except .git
          find wiki -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          # Copy markdown sources
          cp -r docs/* wiki/
          # Normalize links: convert ")(.md)" links to wiki-style without extension across copied files
          # This replaces occurrences of ](path.md) with ](path)
          if command -v sed >/dev/null 2>&1; then
            find wiki -type f -name "*.md" -print0 | xargs -0 sed -i "s/](\([^)#?]*\)\.md)/](\1)/g"
          fi
          # Generate wiki-friendly Home.md (links without .md extensions)
          printf '%s\n' \
            '# TenderBotStore — Документация' \
            '' \
            'Добро пожаловать! Здесь описаны основы платформы и сервисов.' \
            '' \
            '## Быстрые ссылки' \
            '' \
            '- Архитектура → [ER‑схема](architecture/er-schema)' \
            '- Архитектура → [Многотенантность и контекст](architecture/multitenancy)' \
            '- Backend → [Гайд по миграциям (Liquibase)](backend/migrations)' \
            '- Frontend → [Контекст на фронте](frontend/context)' \
            '' \
            '### Сервисы (стабильные)' \
            '' \
            '- [Auth](services/auth)' \
            '- [Context](services/context)' \
            '- [RBAC](services/rbac)' \
            '- [Public Menu](services/menu)' \
            '- [Health](services/health)' \
            '- [Ошибки и коды](services/errors)' \
            > wiki/Home.md
          # Ensure sidebar exists (links without .md extensions)
          if [ ! -f wiki/_Sidebar.md ]; then
            printf '%s\n' \
              '* [Home](Home)' \
              '* [Архитектура](architecture/er-schema)' \
              '* [Многотенантность и контекст](architecture/multitenancy)' \
              '* [RBAC](services/rbac)' \
              '* [Миграции (Liquibase)](backend/migrations)' \
              > wiki/_Sidebar.md
          fi

      - name: Commit and push to Wiki
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update wiki from push $GITHUB_SHA"
            git push
          fi
