name: Frontend CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'Front/**'
      - '.github/workflows/frontend-ci.yml'
#  pull_request:
#    branches: [ "**" ]
#    paths:
#      - 'Front/**'
#      - '.github/workflows/frontend-ci.yml'

jobs:
  test_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Front
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Front/package-lock.json

      - name: Install dependencies
        run: npm ci || npm i

      - name: Run unit tests
        run: npm run test
